version: '3.8'
services:
  coredns:
    image: coredns/coredns:latest
    volumes:
      - /home/elofun/dns/Corefile:/Corefile
      - /home/elofun/dns/elofun.internal.zone:/zones/elofun.internal.zone    
    command:
      - --conf
      - /Corefile
    ports:
      - "53:53/udp"
